### PR TITLE
Removes strict comparison

### PR DESCRIPTION
**Pull request by zvictor**
Currently, the following example would not show any event.

``` js
$('#calendar').fullCalendar({
  defaultView: 'resourceDay',
  // Note that we are using Int values to define the ids.
  resources: [{'id':0,'name':'Resource 1'},{'id':1, 'name':'Resource 2'}], 
  events: [
  {
    title: 'R1-R2: Lunch 14.00-15.00',
    start: '2013-08-21T14:00:00.000Z',
    end: '2013-08-21T15:00:00.000Z',
    // Different type for the ids here: String.
    resources: ['0','1'] 
  }
});
```

This pull request allows the showed example to work by removing the strictness of types when associating resources and events.

### CODE REVIEW

**Comment by zvictor** [comment]
A reference to clarify this issue: [jQuery inArray is always returning -1](http://stackoverflow.com/q/1071441/599991)

**Comment by seankenny** [comment]
Nice catch.

Fails the [Grunt lint tests](https://github.com/arshaw/fullcalendar/wiki/Contributing-Code#development-workflow) though with http://jslinterrors.com/dont-make-functions-within-a-loop

This might be an alternative?

``` javascript
function eventsForResource(resource, events) {
    var resourceEvents = [];

    var hasResource = function(event) {
        if (!event.resources) {
            return false;
        }
        return $.grep(event.resources, function(id) { return id === resource.id; }).length > 0;
    }

    for (var i = 0; i < events.length; i++) {
      if (hasResource(events[i])) {
        resourceEvents.push(events[i]);
      }
    }
    return resourceEvents;
}
```

**Comment by zvictor** [comment]
You are right.
I am fixing it right now = )

**Comment by zvictor** [comment]
Done.

**Pull request merged**
