### PR TITLE
Adds resourceFilter option

### PR DESCRIPTION
**Pull request by zvictor**
Please check `demos/resource-views.html`. Does not need more explanation = )

### CODE REVIEW

**Comment by seankenny** [comment]
I like this one :)  There was a request some time back to allow a hook to filter resources as a user moved forwards/back throught he dates.  This works perfectly for that.

One small issue - uncheck all the resources in the demo page and there is a js undefined exception.  Not too sure how we would cater for no resources returned by a filter?

**Comment by zvictor** [comment]
I think it makes sense to behave in the same way it behaves when there are no events. If I remember well, it renders the entire calendar and its days normally and just does not render the events. I am gonna spend some minutes now trying to get the same here.

**Comment by zvictor** [comment]
Given two scenarios:
1 - Day view without any event;
2 - Resource view without any resource.

When calling `setHeight` on both scenarios we have an inconsistency on this part of the code:

``` haskell
dayBodyFirstCellStretcher
            .height(bodyHeight - vsides(dayBodyFirstCell));
```

On scenario 1, `dayBodyFirstCell` points to the first empty event slot, while in scenario 2 it is `undefined`.

It does not seem to be a bug caused by this PR, but a bug that was already hidden there.

**Comment by seankenny** [comment]
Yes I agree it is appears to be an existing bug.  Let's add your change and
I'll raise an issue on it.

**Pull request merged**
